### ISSUE TITLE
cargo-contract integration

### ISSUE THREAD

**Issue by ascjones** [paritytech/pallet-contracts-waterfall#29]
Explore running `cargo-contract` integration tests against the substrate node as part of the waterfall.

Also looking at the CI PR we could simplify it by using `cargo contract build`. rel https://github.com/paritytech/cargo-contract/issues/6

**Comment by Stefie** [comment]
As discussed on Riot, you @ascjones yourself, @Robbepop & @athei convinced me, that you no longer want that.
I'm therefore closing the issue.
