### ISSUE TITLE
Document how to get a contracts StorageKey

### ISSUE THREAD

**Issue by Stefie** [paritytech/pallet-contracts-waterfall#6]
The StorageKey is needed to request any values from a smart contracts storage.

The plan is to provide a built-in function in srml-contracts to return the StorageKey of any given contract address.

As an interim solution, querying the substrate storage directly will give the required results:

## How To:

**1. Start a new Substrate development node with pruned database or use the docker image in this repository.** 

**2. Deploy and instantiate the smart contract.**

**3. Open a new console window and paste the following code, to get the Keys of all modules in child_storage (currently only smart contracts):**
```
curl -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method":"state_getKeys", "params":["0x3a6368696c645f73746f726167653a"], "id": 0}' -vv http://127.0.0.1:9933/
```
The result should look similar to this:
```{"jsonrpc":"2.0","result":["0x3a6368696c645f73746f726167653a64656661756c743a275d68eb54aaa683c48f8920fc649f281898c92ea09bb0169d032bc808d765a2"],"id":0}```

**4. Copy the returned hex value as a param to this curl request:**

```
curl -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method":"state_getChildKeys", "params": ["YOUR_HEX_VALUE", "0x"], "id": 0}' -vv http://127.0.0.1:9933/
```

Example:
```
curl -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method":"state_getChildKeys", "params": ["0x3a6368696c645f73746f726167653a64656661756c743a275d68eb54aaa683c48f8920fc649f281898c92ea09bb0169d032bc808d765a2", "0x"], "id": 0}' -vv http://127.0.0.1:9933/
``` 
**5. Copy the returned value as your contracts `StorageKey`**

Example reult:
```{"jsonrpc":"2.0","result":["0xf40ceaf86e5776923332b8d8fd3bef849cadb19c6996bc272af1f648d9566a4c"],"id":0}```

In this case, the StorageKey of the contract would be:
```0xf40ceaf86e5776923332b8d8fd3bef849cadb19c6996bc272af1f648d9566a4c```

**Comment by pepyakin** [comment]
Let's close this issue since it is not longer relevant with the new API. Feel free to reopen though if there is something left to do here
