### ISSUE TITLE
CI broken for Solang test

### ISSUE THREAD

**Issue by Stefie** [paritytech/pallet-contracts-waterfall#77]
The CI is throwing an error:
`FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory`

Additional Info:
- All tests are passing locally (with the latest versions)
- Test are passing in the CI, if I'm commenting out the one Solang test
- Cause of the error is the Solang setup in the CI
- The problem has been around for a while, so it's no new behaviour related to any recent changes

I'm pretty sure it has something to do with the node configuration on Gitlab https://devcenter.heroku.com/articles/node-memory-use

**Comment by Stefie** [comment]
Update: Now I'm guessing, that it's related to an outdated version of Solang used in the CI.

**Comment by TriplEight** [comment]
@Stefie Here's how we install `solang` to CI image: https://github.com/paritytech/scripts/blob/master/dockerfiles/contracts-ci-linux/Dockerfile#L45
And it's being updated nightly. So either the newer `solang` version is not stable yet, or the problem is somewhere else.

**Comment by TriplEight** [comment]
https://github.com/trufflesuite/truffle/issues/957#issuecomment-391211564 might help
also https://github.com/Microsoft/vscode/issues/23662#issuecomment-290404628

**Comment by Stefie** [comment]
> Here's how we install solang to CI image:

The version that is published to crates.io is outdated. It hasn't been updated since mid march. The recommended way is to use the docker image.

From @seanyoung:

> the solang crate is pretty out of date. Best to use hyperledger-labs/solang:latest docker file

**Comment by Stefie** [comment]
> trufflesuite/truffle#957 (comment) might help
> also microsoft/vscode#23662 (comment)

No it doesn't, I already tried that yesterday. :|

**Comment by TriplEight** [comment]
>Best to use hyperledger-labs/solang:latest docker file

using the second image in the same CI job is less secure and rather tricky. Moreover, we shouldn't use third-party images since we do not know their security practices.

@seanyoung could you please either suggest a way how to `cargo install` a good `solang` version from github? I mean the exact branch/tag to pass to `cargo install --git` or update it on crates.io? Maybe we will be able to somewhat help with CI for it.

**Comment by seanyoung** [comment]
I'm very close to doing another crates.io release but that's a few days away. For now, the best option is:
```
cargo install --git https://github.com/hyperledger-labs/solang --tag m6
```

**Comment by Stefie** [comment]
How often are you going to release to crates.io? if it's not going to happen regularly in line with the docker images, we should stick to the installation from github.

**Comment by seanyoung** [comment]
I'm hoping to do monthly releases to crates.io, which are more stable. 

Note that on crates.io you can only have dependencies on other crates.io (not git). So this could quickly fall apart. e.g. type-metadata doesn't have a crates.io release but it would be good to use it when possible. Also inkwell releases are irregular.

**Comment by seanyoung** [comment]
github probably safest.

**Comment by TriplEight** [comment]
done https://github.com/paritytech/scripts/pull/200

**Comment by Stefie** [comment]
Test are passing again in the CI
