### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by pepyakin** [paritytech/pallet-contracts-waterfall#9]
Can you help us here, @TriplEight ?

---------------------
- [ ] build contract and run jest tests
- [ ] change settings to 1 PR === 1 commit (SD: no idea where to that)
- [ ] ....?

**Comment by kianenigma** [comment]
Not sure if it is worth a separate issue but: I just skimmed this repo and it is damn loaded with good stuff. While I recall that I sadly saw it a while ago and didn't even get it. So: **Fill the description field please :)**

**Comment by TriplEight** [comment]
Will do

**Comment by pepyakin** [comment]
@Stefie the setting is called ~"Allow squash commit" on the main screen. I turned it on.

**Comment by TriplEight** [comment]
I think it can be closed
